/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#594400",
        "inverse-on-surface": "#f1f1f1",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#474746",
        "surface-tint": "#765b00",
        "outline-variant": "#d2c5ab",
        "surface-variant": "#e2e2e2",
        "tertiary-container": "#73e088",
        "surface": "#f9f9f9",
        "inverse-primary": "#f4bf00",
        "surface-bright": "#f9f9f9",
        "on-primary-fixed": "#241a00",
        "primary-fixed": "#ffdf93",
        "tertiary-fixed-dim": "#70dd85",
        "surface-container-low": "#f3f3f3",
        "primary-container": "#f8c200",
        "background": "#f9f9f9",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#4f4632",
        "primary-fixed-dim": "#f4bf00",
        "on-tertiary-container": "#006229",
        "on-secondary-fixed": "#1b1b1b",
        "secondary-fixed": "#e5e2e1",
        "primary": "#765b00",
        "outline": "#817660",
        "error": "#ba1a1a",
        "surface-container-high": "#e8e8e8",
        "surface-container": "#eeeeee",
        "surface-dim": "#dadada",
        "on-error": "#ffffff",
        "on-background": "#1a1c1c",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary": "#ffffff",
        "secondary": "#5f5e5e",
        "on-tertiary-fixed": "#002109",
        "on-secondary-container": "#636262",
        "tertiary-fixed": "#8cfa9f",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary": "#ffffff",
        "tertiary": "#006e2e",
        "on-error-container": "#93000a",
        "secondary-container": "#e2dfde",
        "on-tertiary-fixed-variant": "#005321",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#695100",
        "inverse-surface": "#2f3131",
        "error-container": "#ffdad6",
        success: "#16A34A",
        danger: "#DC2626",
        warning: "#D97706",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Inter"],
        label: ["Inter"],
        sans: ["'Inter'", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
    },
  },
  plugins: [],
};
